name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run lint and tests
        run: |
          npm run lint
          npm test

      - name: Build Windows App
        run: npm run dist:win

      - name: List dist folder
        run: dir dist

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: neoncore-dist
          path: dist/**/*