name: Build & Release (Windows)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        shell: pwsh

      - name: Run lint and tests
        run: |
          npm run lint
          npm test
        shell: pwsh

      - name: Build Windows App
        run: npm run dist:win
        shell: pwsh

      - name: Ensure dist folder exists and add placeholder if empty
        shell: pwsh
        run: |
          if (!(Test-Path -Path dist)) {
            New-Item -ItemType Directory -Path dist | Out-Null
          }
          if ((Get-ChildItem -Path dist | Measure-Object).Count -eq 0) {
            '<placeholder>' | Out-File dist\placeholder.txt
          }

      - name: List dist folder
        shell: pwsh
        run: Get-ChildItem -Path dist

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: neoncore-dist
          path: dist